2025-01-16 10:09:46,398 ! WARNING ! Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "/Users/sibmurzik/PycharmProjects/PythonProject/pdf_to_doc/Module12/runner_test.py", line 25, in test_run
    men = Runner(10)
  File "/Users/sibmurzik/PycharmProjects/PythonProject/pdf_to_doc/Module12/rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2025-01-16 10:09:46,399 ! WARNING ! Неверная скорость для Runner
Traceback (most recent call last):
  File "/Users/sibmurzik/PycharmProjects/PythonProject/pdf_to_doc/Module12/runner_test.py", line 12, in test_walk
    men = Runner('Ralf', speed= -5)
  File "/Users/sibmurzik/PycharmProjects/PythonProject/pdf_to_doc/Module12/rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
